### ISSUE TITLE
Parse 2-level adoptions: e.g. "EN ISO", "CEN ISO"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-bsi#10]
These are 2-level adoptions:
* ISO/IEC publishes a standard
* EN or CEN adopts the ISO/IEC standard
* BS or PD or DD adopts the EN/CEN standard

```
BS EN ISO 13485:2012
BS EN ISO 13485:2016
BS EN ISO 13485:2016+A11:2021
BS EN ISO 14971:2012
BS EN ISO 20607:2019
BS EN ISO 56000
BS EN ISO 56002
BS EN ISO 56003
BS EN ISO 898-1:2013
BS EN IEC 62305-4
BS EN IEC 62368-1:2020+A11:2020 
PD CEN ISO/TR 20173:2018
BS EN ISO/IEC 17025:2017
BS EN ISO/IEC 80079-34:2020 ED2
```

**Comment by mico** [comment]
@ronaldtse what "EN" and "CEN" stand for?

**Comment by ronaldtse** [comment]
* EN = "European Norm" (which means European Standard).
* CEN = Center for European Normalization (the equivalent of ISO in the EU)
* CLC = European Committee for Electrotechnical Standardization (the equivalent of IEC in the EU)

Both CEN and CLC publish documents in their prefixes, e.g.:
* By CEN only:
    * CEN/TR 17833:2022
    * CEN/TS 17638:2021
* By CLC only:
    * CLC/TR 62125:2008
    * CLC/TS 50701:2021
* Copublished:
    * CEN/CLC/TR 17602-80-12:2021
    * CEN/CLC/TS 17880:2022

ENs are published by one of 3 organizations: CEN, CLC, and ETSI.

CEN and CLC can publish ENs:
* EN 16602-60-15:2014
* EN 17355:2020

This task is dependent on:
* [ ] https://github.com/metanorma/pubid-cen/issues/1

**Comment by mico** [comment]
Also need to consider parsing "IEC" identifiers like "BS EN 60038 AMD1 FRAG2".
https://github.com/metanorma/pubid-bsi/issues/2#issuecomment-1459112979
