### ISSUE TITLE
Parse National Annexes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-bsi#18]
NA+A2:2022 to BS EN 1997-1:2004+A1:2013
NA+A2:18 to BS EN 1991-1-3:2003+A1:2015
NA to BS EN 1996-1-1:2005+A1:2012
NA to BS EN 1993-3-1:2006
NA to BS EN 1997-2:2007
NA to BS EN 1991-4:2006
NA to BS EN 1993-6:2007
NA+A1:2012 to BS EN 1993-5:2007
NA+A1:2014 to BS EN 1993-1-1:2005+A1:14
NA+A1:2014 to BSEN1991-1-7:2006+A1:2014
NA to BS EN 1999-1-2:2007
NA+A1:15 to BS EN 1993-1-4:2006+A1:2015

**Comment by mico** [comment]
> NA+A1:2014 to BSEN1991-1-7:2006+A1:2014

@ronaldtse The spaces missing here. Should we parse this or raise an error?

**Comment by ronaldtse** [comment]
> Should we parse this or raise an error? 

If we can parse it, great. If not, just raise an error.
