### ISSUE TITLE
Parse identifiers with Amendment

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-bsi#2]
`BS 7273-4:2015+A1:2021` means this document is `BS 7273-4:2015` incorporating the Amendment `A1` published in `2021`.

```
BS 4592-0:2006+A1:2012
BS 1192:2007+A2:2016
BS 4142:2014+A1:2019
BS 5228-1:2009+A1:2014
BS 7273-4:2015+A1:2021
BS 8500-1:2015+A2:2019
BS 8500-2:2015+A2:2019
PAS 5678:2005+A1:2009
PAS 5678-2:2005+A1:2009
PD 5500:2021+A2:2022
```

This task depends on:
* #1 
* #4 
* #5

**Comment by mico** [comment]
I also found Amendments like this: https://knowledge.bsigroup.com/products/bs-en-60038-amd1-frag2-standard-voltages-for-ac-supply-and-ac-equipment-proposed-horizontal-standard/standard (`BS EN 60038 AMD1 FRAG2`)

**Comment by ronaldtse** [comment]
The "FRAG{n}" notation is an IEC one. A "Fragment" means it is a part of an Amendment. This we should implement in IEC.

**Comment by mico** [comment]
> The "FRAG{n}" notation is an IEC one. A "Fragment" means it is a part of an Amendment. This we should implement in IEC.

@ronaldtse "FRAG{n}" already implemented in pubid-iec.
How should I parse "BS EN 60038 AMD1 FRAG2"? There are no signs of IEC identifier. Only "FRAG{n}".

**Comment by ronaldtse** [comment]
Interestingly there is a way to tell IEC standards. IEC numbers start from 60000 to 79999. From 80000-89999 they are either ISO, IEC, or ISO/IEC or IEC/ISO standards. From 1 to 59999 it is only ISO.
