### ISSUE TITLE
Parse translations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-bsi#20]
PAS 9017:2020+C1 SPANISH TRANSLATION
BS 25999-1:2006 (German)
BS 25999-1:2006 (French)
BS 25999-2:2007 (French)
PAS 402:2009 (Welsh)
PAS 78:2006 WELSH TRANSLATION
PAS 99:2006 (Italian Translation)
PAS 99:2006 (Spanish Translation)
BS 25999-2:2007 (German)
BS ISO/IEC 17799:2005 (French version)
PAS 1018:2017 (Cantonese)
PAS 186:2020 (Chinese)
PAS 13:2017 (Italian)

**Comment by mico** [comment]
@ronaldtse what should be standardized output for the language? Something like `(French)`?

**Comment by ronaldtse** [comment]
Agree, let's use this convention.
