### ISSUE TITLE
Parse documents with Amendments or Corrigenda included

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-bsi#21]
BS EN 55014-1:2017+A11:2020
BS EN IEC 60238:2018+A11:2021
BS EN IEC 60947-5-2:2020+A11:2022
BS EN ISO 11203:2009+A1:2020
BS EN ISO 80601-2-56:2017+A1:2020
BS EN 60335-2-35:2016+A2:2021
BS EN 13480-5:2017+A2:2021
BS EN 60335-2-12:2003+A2:2019
BS EN 14915:2013+A2:2020
PD 5500:2018+A3:2020
PD 5500:2015+A3:2017
PD IEC TS 63134:2020+A1:2022
PAS 3002:2018+C1:2018
PAS 2035/2030:2019+A1:2022
PAS 4444:2020+A1:2021
PAS 24:2007+A2:2011
PD IEC TR 60919-3:2009+A2:2021
PD CISPR TR 16-4-5:2006+A2:2021
PAS 2035:2019+C2:2021
PAS 2030:2019+C2:2021

**Comment by mico** [comment]
@ronaldtse isn't it the same as #2 but with corrigenda?

**Comment by ronaldtse** [comment]
Yes it is. And here we also have adoption identifiers with A and C.

**Comment by mico** [comment]
> BS EN IEC 60238:2018+A11:2021

@ronaldtse hard to figure out if it is BS amendment or EN
