### ISSUE TITLE
Gem is not accepting expert_commentary parameter

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-bsi#36]
The pubid-bsi gem that has been released is not accepting `expert_commentary` as a parameter

The code on this repository does, but since there is no indication of release or even release tag on this repository, I have no way of seeing on the repository which version of the code has been released as the current gem. The released gem, on inspection, is not parsing that parameter.

Please consult @CAMOBAP on how Ribose gems are released through github. Release tags must be used, so we can tell what code is being used in what version of the gem.

Please release current version of pubid-bsi, so that I can continue with https://github.com/metanorma/metanorma-bsi/issues/385

**Comment by ronaldtse** [comment]
For @opoudjis :

> The pubid-bsi gem that has been released is not accepting expert_commentary as a parameter

The `expert_commentary` part is currently being re-worked into a DocumentType. It is not ready.

Also, the v0.1.1 release did not include any expert_commentary support, it was merged in 17ed97c94c8e562f9dd13dc58cb4d0928820e840 which is a few days after v0.1.1 was released.


For @mico:

All pubid-* gems are meant to be released through the release.yml workflow by using new Git tags such as `v0.1.1`.

Currently, this gem is released via a manual trigger of release.yml:
* https://github.com/metanorma/pubid-bsi/actions/workflows/release.yml

I have tagged the v0.1.1 release with the corresponding commit for that release.
