### ISSUE TITLE
Parse Flex identifiers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-bsi#6]
Flex is a new type of document published by BSI, which is like a PAS but with faster production.

The identifier pattern has two differences:
1. Can include a version (edition) number
2. Can provide the month 

```
BSI Flex 0 v2.0:2022-08
BSI Flex 1889 v1.0:2022-07
BSI Flex 8670 v3.0:2021-04
Flex 0:2022
Flex 1889
Flex 1890
Flex 5555
Flex 8670 v3.0:2021-04
Flex 8670:2021
Flex 8670:2021-04
```

**Comment by mico** [comment]
@ronaldtse I see two patterns for prefix here:
"BSI Flex" and "Flex". Which one I should follow for the output?

**Comment by ronaldtse** [comment]
I believe we should use "BSI Flex" and "BSI PAS". Can you also document this in the README? Thanks.

**Comment by mico** [comment]
> I believe we should use "BSI Flex" and "BSI PAS". The rest of the document types can be as they are, i.e. "BS", "PD", etc. Can you also document this in the README? Thanks.

@ronaldtse Do you mean:
- BSI Flex 123
- BSI PAS 123

But:
- BS 123
- PD 123


Did I get it right?

**Comment by ronaldtse** [comment]
Yes that’s correct. Because outside of BSI documents, a “BS xxx” is still called a “BS xxx”, not a “BSI BS xxx”. But a Flex and PAS will have the prefix of “BSI” in front.
